-- ============================================================
--  Wanteermako — Import de 20 produits AliExpress (catalogue affilié)
--  À exécuter dans Supabase → SQL Editor (PAS via l'admin).
--
--  👉 1 SEULE chose à changer : mets ton numéro WhatsApp ligne « v_wa ».
--  Le bouton « Commander sur WhatsApp » enverra les clients vers ce numéro.
--  Les liens affiliés AliExpress sont stockés en privé (external_url).
-- ============================================================
do $$
declare
  v_owner uuid := (select id from public.profiles where email ilike 'multiservicesyamane@gmail.com' limit 1);
  v_wa text := '221770000000';   -- 👈👈 REMPLACE par TON numéro WhatsApp (avec indicatif, ex: 221771234567)
begin
  if v_owner is null then
    raise exception 'Compte propriétaire introuvable. Connecte-toi une fois sur le site avec multiservicesyamane@gmail.com puis relance.';
  end if;

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble Baseus USB-C charge rapide (iPhone & Android)', 'cable-baseus-usb-c-charge-rapide-iphone-android-0h5wk', 'Câble Baseus USB-C charge rapide (iPhone & Android). Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '2500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S0731bd0614504a5198455479dda8d54eI.png', 'https://s.click.aliexpress.com/e/_c4Od634V', v_wa, 'aliexpress', 'active', true, true, true, true, 'alaune');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche bras long déco (cadeau)', 'coussin-peluche-bras-long-deco-cadeau-yzr4c', 'Coussin peluche bras long déco (cadeau). Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '12500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S65c3d2eaef7044e0bd65d49f81d62a1a7.jpg', 'https://s.click.aliexpress.com/e/_c2uvFMAz', v_wa, 'aliexpress', 'active', true, true, true, true, 'alaune');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Écouteurs Bluetooth Lenovo LE209', 'ecouteurs-bluetooth-lenovo-le209-f9nzd', 'Écouteurs Bluetooth Lenovo LE209. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '10000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S22f9e48f9d874687a682731748f3dd83O.png', 'https://s.click.aliexpress.com/e/_c3nYR07J', v_wa, 'aliexpress', 'active', true, true, true, true, 'alaune');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier initiale plaqué or 18K (A-Z)', 'collier-initiale-plaque-or-18k-a-z-04j8j', 'Collier initiale plaqué or 18K (A-Z). Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '1000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S9231a1e540d54ab9a0fa34603e6ca4988.jpg', 'https://s.click.aliexpress.com/e/_c3L1Urrn', v_wa, 'aliexpress', 'active', true, true, true, true, 'alaune');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Peluche animal de la forêt – oreiller doux', 'peluche-animal-de-la-foret-oreiller-doux-bj1kj', 'Peluche animal de la forêt – oreiller doux. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '7000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa15f6ea58c884cb7b3618b16d1c4dd33F.jpg', 'https://s.click.aliexpress.com/e/_c3iVQFKh', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre connectée LIGE 2026 (homme & femme)', 'montre-connectee-lige-2026-homme-femme-4v6bq', 'Montre connectée LIGE 2026 (homme & femme). Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '11500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa219b54be5f046aab538bdfd09785768z.jpg', 'https://s.click.aliexpress.com/e/_c4BdcgqV', v_wa, 'aliexpress', 'active', true, true, true, true, 'alaune');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Support téléphone pliable avec charge rapide', 'support-telephone-pliable-avec-charge-rapide-kxsj0', 'Support téléphone pliable avec charge rapide. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '1500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S170bdbf66ddd4b6097de46611412eb8cD.jpg', 'https://s.click.aliexpress.com/e/_c3lMzfJb', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boucles d''oreilles Moissanite argent 925', 'boucles-d-oreilles-moissanite-argent-925-69yom', 'Boucles d''oreilles Moissanite argent 925. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '6000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sdc5c2fdeb31045d8b34cef7ef0107250C.jpg', 'https://s.click.aliexpress.com/e/_c3X7MXdB', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Miroir de maquillage LED 3 couleurs', 'miroir-de-maquillage-led-3-couleurs-m9agh', 'Miroir de maquillage LED 3 couleurs. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '5500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S5f42918fa1f0421c9d30ee47925b9f9dN.jpg', 'https://s.click.aliexpress.com/e/_c3xSI5Ip', v_wa, 'aliexpress', 'active', true, true, true, true, 'alaune');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lunettes de soleil rétro Y2K (femme & homme)', 'lunettes-de-soleil-retro-y2k-femme-homme-p4p2t', 'Lunettes de soleil rétro Y2K (femme & homme). Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '7500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S15fb9e5c616943fbb9940d091d9d7d091.jpg', 'https://s.click.aliexpress.com/e/_c3CzCnAt', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Trousse de maquillage femme', 'trousse-de-maquillage-femme-jao15', 'Trousse de maquillage femme. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '2000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sdd29732fa6604cefbf62877837126f25D.jpg', 'https://s.click.aliexpress.com/e/_c3OC4w2V', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Casque Bluetooth tactile HTC NE70', 'casque-bluetooth-tactile-htc-ne70-vbmc9', 'Casque Bluetooth tactile HTC NE70. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '15000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S4e179339ba7347b2b92aa3ccb0a862d0e.png', 'https://s.click.aliexpress.com/e/_c32A1uzF', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Pelle à pizza en aluminium', 'pelle-a-pizza-en-aluminium-x42n1', 'Pelle à pizza en aluminium. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '12000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa2c35a84734a453f95ebc8afd1c040bcV.png', 'https://s.click.aliexpress.com/e/_c4ed7woD', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boucles d''oreilles créoles zircon', 'boucles-d-oreilles-creoles-zircon-l8492', 'Boucles d''oreilles créoles zircon. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '4000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S7aa13f37936f49ea95efce173706e2e4q.jpg', 'https://s.click.aliexpress.com/e/_c3wn9NkV', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boomerang volant rotatif (jouet enfant)', 'boomerang-volant-rotatif-jouet-enfant-5mget', 'Boomerang volant rotatif (jouet enfant). Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '6000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S20bd1285c755440292cc3f33e7a62717e.jpg', 'https://s.click.aliexpress.com/e/_c2wC2uMh', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Écouteurs sans fil TWS HTC NE49', 'ecouteurs-sans-fil-tws-htc-ne49-oa3li', 'Écouteurs sans fil TWS HTC NE49. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '11500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sc002fb19429c44ad93deca50d5c4fde7n.png', 'https://s.click.aliexpress.com/e/_c3VUXBLx', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Pinceaux de maquillage Jessup (10-14 pièces)', 'pinceaux-de-maquillage-jessup-10-14-pieces-5gxwe', 'Pinceaux de maquillage Jessup (10-14 pièces). Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '16000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S355f3d3bfd05427686ffef95014378abN.jpg', 'https://s.click.aliexpress.com/e/_c4oQMvc9', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Écouteurs TWS Bluetooth 5.4 faible latence', 'ecouteurs-tws-bluetooth-5-4-faible-latence-8vhsr', 'Écouteurs TWS Bluetooth 5.4 faible latence. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '12000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S68d6dea8e9924ba7bf8d40d1a287e9ebT.jpg', 'https://s.click.aliexpress.com/e/_c30DV1x3', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre mécanique homme cadran transparent', 'montre-mecanique-homme-cadran-transparent-874nf', 'Montre mécanique homme cadran transparent. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '19000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Hec30fa48a9d74f8ca5050c0bf8d50af49.jpg', 'https://s.click.aliexpress.com/e/_c2JvCZkl', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bracelet nylon pour montre Garmin Fenix', 'bracelet-nylon-pour-montre-garmin-fenix-hhnmh', 'Bracelet nylon pour montre Garmin Fenix. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande rapidement.', '17500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sb5c1873ab60e4624bd114dbc0ce4e36bn.jpg', 'https://s.click.aliexpress.com/e/_c41sx3ln', v_wa, 'aliexpress', 'active', true, true, false, false, 'premium');

  raise notice '✅ 20 produits importés avec succès !';
end $$;

-- Vérifier : select title, price, order_whatsapp from public.listings where source = 'aliexpress' order by created_at desc;
