-- ============================================================
--  Wanteermako — Réserve de 97 produits AliExpress (DÉSACTIVÉS)
--  À exécuter dans Supabase → SQL Editor (PAS via l'admin).
--
--  Les 97 produits sont créés en statut « inactive » (désactivés)
--  dans ton compte multiservicesyamane. Tu les ACTIVES un par un quand
--  tu veux (Dashboard → Mes annonces, ou Admin → Modération/Annonces).
--
--  👉 1 SEULE chose à changer : ton numéro WhatsApp (ligne « v_wa »).
-- ============================================================

-- Colonnes nécessaires (créées automatiquement si absentes)
alter table public.listings add column if not exists external_url text;
alter table public.listings add column if not exists source text;
alter table public.listings add column if not exists order_whatsapp text;

do $$
declare
  v_owner uuid := (select id from auth.users where email ilike 'multiservicesyamane@gmail.com' limit 1);
  v_wa text := '221776827851';   -- Numéro WhatsApp de commande (Wanteermako)
begin
  if v_owner is null then
    raise exception 'Compte multiservicesyamane introuvable. Connecte-toi une fois sur le site avec ce compte puis relance.';
  end if;

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boîte de rangement', 'boite-de-rangement-snlnx', 'Boîte de rangement. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Se491a25f27bc417c81cde472b0588fbfh.jpg', 'https://s.click.aliexpress.com/e/_c2wuRx5R', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge Baseus', 'cable-de-charge-baseus-ud528', 'Câble de charge Baseus. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '2500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S0731bd0614504a5198455479dda8d54eI.png', 'https://s.click.aliexpress.com/e/_c4Od634V', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche', 'coussin-peluche-rwl20', 'Coussin peluche. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S65c3d2eaef7044e0bd65d49f81d62a1a7.jpg', 'https://s.click.aliexpress.com/e/_c2uvFMAz', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Casque Bluetooth Lenovo', 'casque-bluetooth-lenovo-e4gwq', 'Casque Bluetooth Lenovo. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '10000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S22f9e48f9d874687a682731748f3dd83O.png', 'https://s.click.aliexpress.com/e/_c3nYR07J', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-abe52', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '1000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S9231a1e540d54ab9a0fa34603e6ca4988.jpg', 'https://s.click.aliexpress.com/e/_c3L1Urrn', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Casque Bluetooth', 'casque-bluetooth-s23xw', 'Casque Bluetooth. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '10000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sb553de55331b469caf22d9ac025a83f4k.jpg', 'https://s.click.aliexpress.com/e/_c3h9B3pX', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Jouet', 'jouet-zshba', 'Jouet. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '5500', 'Prix Fixe', 'Sports, Loisirs & Culture', 'sport', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S334c09266f34470181c13b6b1a1e5122E.jpg', 'https://s.click.aliexpress.com/e/_c3LPyyil', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-hr2pt', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '9000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Se6340ba37529468eb40c0e514ce320dcd.jpg', 'https://s.click.aliexpress.com/e/_c3O87spJ', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche', 'coussin-peluche-cku5p', 'Coussin peluche. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '7000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa15f6ea58c884cb7b3618b16d1c4dd33F.jpg', 'https://s.click.aliexpress.com/e/_c3iVQFKh', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Jouet', 'jouet-hfa0k', 'Jouet. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '2500', 'Prix Fixe', 'Sports, Loisirs & Culture', 'sport', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S8e38a7e55ca1459783679dd92526f288Z.jpg', 'https://s.click.aliexpress.com/e/_c4qilNOt', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre connectée Lige', 'montre-connectee-lige-nljq4', 'Montre connectée Lige. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '11500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa219b54be5f046aab538bdfd09785768z.jpg', 'https://s.click.aliexpress.com/e/_c4BdcgqV', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Jouet', 'jouet-4lwpi', 'Jouet. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '20000', 'Prix Fixe', 'Sports, Loisirs & Culture', 'sport', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S0b8b8a23c4c043798d08cffab88b948cJ.jpg', 'https://s.click.aliexpress.com/e/_c35YOi5x', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge Samsung', 'cable-de-charge-samsung-8s9gu', 'Câble de charge Samsung. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '1500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S170bdbf66ddd4b6097de46611412eb8cD.jpg', 'https://s.click.aliexpress.com/e/_c3lMzfJb', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boucles d''oreilles', 'boucles-d-oreilles-lv89m', 'Boucles d''oreilles. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '6000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sdc5c2fdeb31045d8b34cef7ef0107250C.jpg', 'https://s.click.aliexpress.com/e/_c3X7MXdB', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Maquillage', 'maquillage-0kzbz', 'Maquillage. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '5500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S5f42918fa1f0421c9d30ee47925b9f9dN.jpg', 'https://s.click.aliexpress.com/e/_c3xSI5Ip', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lunettes de soleil', 'lunettes-de-soleil-9nur8', 'Lunettes de soleil. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '7500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S15fb9e5c616943fbb9940d091d9d7d091.jpg', 'https://s.click.aliexpress.com/e/_c3CzCnAt', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Trousse de maquillage', 'trousse-de-maquillage-gde5r', 'Trousse de maquillage. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '2000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sdd29732fa6604cefbf62877837126f25D.jpg', 'https://s.click.aliexpress.com/e/_c3OC4w2V', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Écouteurs sans fil TWS Htc', 'ecouteurs-sans-fil-tws-htc-az2vs', 'Écouteurs sans fil TWS Htc. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '15000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S4e179339ba7347b2b92aa3ccb0a862d0e.png', 'https://s.click.aliexpress.com/e/_c32A1uzF', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Ustensile de cuisine', 'ustensile-de-cuisine-d30ze', 'Ustensile de cuisine. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa2c35a84734a453f95ebc8afd1c040bcV.png', 'https://s.click.aliexpress.com/e/_c4ed7woD', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boucles d''oreilles', 'boucles-d-oreilles-l493l', 'Boucles d''oreilles. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S7aa13f37936f49ea95efce173706e2e4q.jpg', 'https://s.click.aliexpress.com/e/_c3wn9NkV', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lampe LED', 'lampe-led-e4c6z', 'Lampe LED. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '6000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S20bd1285c755440292cc3f33e7a62717e.jpg', 'https://s.click.aliexpress.com/e/_c2wC2uMh', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-kmv8c', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '8000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sfbde226b1dc54b61927d64e42a6804fa4.jpg', 'https://s.click.aliexpress.com/e/_c30xJwmd', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Écouteurs sans fil TWS Htc', 'ecouteurs-sans-fil-tws-htc-vomgw', 'Écouteurs sans fil TWS Htc. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '11500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sc002fb19429c44ad93deca50d5c4fde7n.png', 'https://s.click.aliexpress.com/e/_c3VUXBLx', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-53roa', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '20500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S84368613d03747e18a0c3e9901e40180C.jpg', 'https://s.click.aliexpress.com/e/_c3tXBPn3', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre Huawei', 'montre-huawei-q9lob', 'Montre Huawei. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '2500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S3025daf264414ba38fb78e3811fbffcbN.jpg', 'https://s.click.aliexpress.com/e/_c3KiVtK1', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Ustensile de cuisine Hoco', 'ustensile-de-cuisine-hoco-wehn6', 'Ustensile de cuisine Hoco. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sbbebc87ab43244c98770ecc8df3248f9e.jpg', 'https://s.click.aliexpress.com/e/_c3MTWQBP', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-henkt', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '9500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Se168982d079d4cc59f056ad1529ed09e2.jpg', 'https://s.click.aliexpress.com/e/_c3YDi8BX', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-atvtv', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '7500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sde6f0c3428de4c88be384d0038d36063r.jpg', 'https://s.click.aliexpress.com/e/_c45JU5Ul', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-bud9w', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S2d13fe3d678148aeaf2eaebfe6389b9dB.jpg', 'https://s.click.aliexpress.com/e/_c3V86Kgh', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Support téléphone', 'support-telephone-i3evp', 'Support téléphone. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '16500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa91211b8975a4455bca53486f2bbec1bi.jpg', 'https://s.click.aliexpress.com/e/_c4mwSZ9f', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Miroir LED maquillage', 'miroir-led-maquillage-g2m23', 'Miroir LED maquillage. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '11000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S9a39c206b8b3435e8b2148ce49cc6466R.jpg', 'https://s.click.aliexpress.com/e/_c3ZDFSmd', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-ybebf', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '9000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S06d5f708102842d39a005eb12eeb275fq.jpg', 'https://s.click.aliexpress.com/e/_c368voWN', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-mto7h', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '3000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Scf287eb223994d9a83acd2271888670cE.jpg', 'https://s.click.aliexpress.com/e/_c2wsbnNT', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Support téléphone', 'support-telephone-agvy4', 'Support téléphone. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '22500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S0326199dcfd4487392c99e26802ec528q.jpg', 'https://s.click.aliexpress.com/e/_c3RpHhBF', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-hj3a7', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '5000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Saab684ad9c924d93b9b908ca9dde1848h.jpg', 'https://s.click.aliexpress.com/e/_c4V4m8ut', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-4ntcp', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S22741143d28c49fcb27e8b73dec67b45C.jpg', 'https://s.click.aliexpress.com/e/_c4MHKrFb', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-5qacf', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '1000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S947f7a4e17fa4c9f8f346609eac83921S.jpg', 'https://s.click.aliexpress.com/e/_c4501Vd7', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-mah3p', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '20000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S841e1cc4c436474f854c283b62d8d198H.jpg', 'https://s.click.aliexpress.com/e/_c3jxsqw5', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lampe LED', 'lampe-led-sdwk8', 'Lampe LED. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '25500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S98c139e298a54a10aec765aa54377190F.png', 'https://s.click.aliexpress.com/e/_c2ylgPF3', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-30gaz', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '13500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Se6ed09d150154cfa92d5d900ee931317X.jpg', 'https://s.click.aliexpress.com/e/_c2I75oad', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-r6773', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sba7a8403107b403da04f51feac7c4868G.jpg', 'https://s.click.aliexpress.com/e/_c3dxrzVB', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Miroir LED maquillage', 'miroir-led-maquillage-30zhu', 'Miroir LED maquillage. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '11000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sbebd3a6bfb6c4744aea650c8b39047457.jpg', 'https://s.click.aliexpress.com/e/_c4rJJrEZ', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boucles d''oreilles', 'boucles-d-oreilles-yqnbq', 'Boucles d''oreilles. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '5500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S37d033cb9eff4d6f966bdaf6b9af895e1.jpg', 'https://s.click.aliexpress.com/e/_c4CWYmdx', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bracelet', 'bracelet-a1ip6', 'Bracelet. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '13000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S441814511adb4a28a4d32174a95c888cO.jpg', 'https://s.click.aliexpress.com/e/_c3hxQt49', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lunettes de soleil', 'lunettes-de-soleil-xkhyk', 'Lunettes de soleil. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '9000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sab144a28ba6b4cec89f2b52d9225ab58M.jpg', 'https://s.click.aliexpress.com/e/_c3iOgbID', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-d54nz', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S272f7d0b8de64283b8844591077463d1W.jpg', 'https://s.click.aliexpress.com/e/_c2RMSJsl', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-ndh6f', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '5500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/H02224be235f543db994020f9cf7c0c108.jpg', 'https://s.click.aliexpress.com/e/_c3UnsEop', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-ggj8m', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sc7a06727901946ecb794dd0171387ed5j.jpg', 'https://s.click.aliexpress.com/e/_c4UdqRLT', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Support téléphone', 'support-telephone-hstx2', 'Support téléphone. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '15000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S6a7ddb4c8c5e43fe8ccf2bdb56fed5e7T.jpg', 'https://s.click.aliexpress.com/e/_c30arKsZ', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lunettes de soleil', 'lunettes-de-soleil-r8iv0', 'Lunettes de soleil. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '14000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S11530c93bceb4563ad29b138abfa8c2es.jpg', 'https://s.click.aliexpress.com/e/_c3gt2NDX', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-5qx5d', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '24000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S823a8af641234322bc7ab1e04e2417e6A.jpg', 'https://s.click.aliexpress.com/e/_c4LjCogt', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Miroir LED maquillage', 'miroir-led-maquillage-56vcw', 'Miroir LED maquillage. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '11000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S8add93f0485c4b55b55241bd2bcd5718d.jpg', 'https://s.click.aliexpress.com/e/_c4PDQ2el', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bracelet', 'bracelet-p80mf', 'Bracelet. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '5000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S02517371229942cba8abbe833c35c903Z.jpg', 'https://s.click.aliexpress.com/e/_c2zt4VPT', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-8kpcz', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '7000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sddd45826bfd046b5b8f1082899783172c.png', 'https://s.click.aliexpress.com/e/_c3lftJ1X', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boucles d''oreilles', 'boucles-d-oreilles-n4jck', 'Boucles d''oreilles. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S5ed90b5965e747d6a8d4a9f5e8bbbb59d.jpg', 'https://s.click.aliexpress.com/e/_c4CNX46H', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Pinceaux de maquillage Jessup', 'pinceaux-de-maquillage-jessup-jl3i2', 'Pinceaux de maquillage Jessup. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '16000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S355f3d3bfd05427686ffef95014378abN.jpg', 'https://s.click.aliexpress.com/e/_c4oQMvc9', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-227kw', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '6000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S1f46100585014ac6a5e08a776b7d8fc4K.jpg', 'https://s.click.aliexpress.com/e/_c3WUKiOl', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche', 'coussin-peluche-g3e4w', 'Coussin peluche. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '15000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa27212c27102455eba4c1a52be1c5d6dZ.jpg', 'https://s.click.aliexpress.com/e/_c3Skr2G1', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lunettes de soleil', 'lunettes-de-soleil-wfb8t', 'Lunettes de soleil. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '24000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S75a51bb100c34abd80e3fa86a5d930bcA.jpg', 'https://s.click.aliexpress.com/e/_c3aNa1Ih', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-muv71', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '7500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S4cae25e6ac23438aa875147c26dd09c5J.jpg', 'https://s.click.aliexpress.com/e/_c2IWZ9yH', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-61tja', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '6000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S5e56376a31534614b7ac83ecbc2d4e2ck.png', 'https://s.click.aliexpress.com/e/_c3vRBzfL', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-c22zv', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S7d6264aae5364320a9334397040805aaJ.jpg', 'https://s.click.aliexpress.com/e/_c4SSN1E1', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-e5uwa', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '3500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S43b73dee96d649e38aea089e0b9a5f04l.jpg', 'https://s.click.aliexpress.com/e/_c3nN0lwt', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-2naab', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '8500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sd226f283ac7c48d5a2e6580a5acb1f11O.jpg', 'https://s.click.aliexpress.com/e/_c3IidH3T', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche', 'coussin-peluche-iln1f', 'Coussin peluche. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S0f6307a386fc479f9321e125431023f4v.jpg', 'https://s.click.aliexpress.com/e/_c4EOLtqD', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Lunettes de soleil', 'lunettes-de-soleil-dmgc6', 'Lunettes de soleil. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '11000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S61867d7669f64c0fbdd5ac7156eb55711.jpg', 'https://s.click.aliexpress.com/e/_c35svAG1', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Collier', 'collier-1ot7o', 'Collier. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '3500', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S4d0ccade7c8f4390a48198e0f39b5f06H.jpg', 'https://s.click.aliexpress.com/e/_c4cTxgMZ', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche', 'coussin-peluche-w8dlg', 'Coussin peluche. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sc8b9e87c8c754b29b23c2717f2fbac21j.jpg', 'https://s.click.aliexpress.com/e/_c2xzXS9T', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Écouteurs sans fil TWS', 'ecouteurs-sans-fil-tws-ju1mf', 'Écouteurs sans fil TWS. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S68d6dea8e9924ba7bf8d40d1a287e9ebT.jpg', 'https://s.click.aliexpress.com/e/_c30DV1x3', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Chargeur rapide', 'chargeur-rapide-0umt2', 'Chargeur rapide. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '8000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S7f90a825dd7e445bb75ed5eef5b4721dF.jpg', 'https://s.click.aliexpress.com/e/_c4szToGv', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bague', 'bague-htnqb', 'Bague. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '16000', 'Prix Fixe', 'Mode, Beauté & Accessoires', 'mode', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S8fd5812e9ab84f29b45c4c709eab9d45u.jpg', 'https://s.click.aliexpress.com/e/_c356cD9P', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-xgna6', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S9c2604445f7944ada55472f8e2b66c18H.png', 'https://s.click.aliexpress.com/e/_c4TvlXU9', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-lsx8y', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '19000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Hec30fa48a9d74f8ca5050c0bf8d50af49.jpg', 'https://s.click.aliexpress.com/e/_c2JvCZkl', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-oi3i5', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '10500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sc78591072ea345e2822d3bb61fd17119S.jpg', 'https://s.click.aliexpress.com/e/_c3WTjbEv', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-8d1a8', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '24500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S2cf1a5311e16459ea3fe9e5c8ec76b6dU.jpg', 'https://s.click.aliexpress.com/e/_c2JfLi4h', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre Garmin', 'montre-garmin-bd9z0', 'Montre Garmin. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '17500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sb5c1873ab60e4624bd114dbc0ce4e36bn.jpg', 'https://s.click.aliexpress.com/e/_c41sx3ln', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coque téléphone', 'coque-telephone-ekp6s', 'Coque téléphone. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '5500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S4239248319574aa69b8a620c91b72a66n.jpg', 'https://s.click.aliexpress.com/e/_c3ah9YKH', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Chargeur rapide', 'chargeur-rapide-qoad6', 'Chargeur rapide. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '10000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S30ae8fddc0bb47839141a109ba8b74e2P.jpg', 'https://s.click.aliexpress.com/e/_c4Sai6Rn', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Miroir LED maquillage', 'miroir-led-maquillage-ejfza', 'Miroir LED maquillage. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '8500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sf5b6adcb7ada42d89536ffee483af7b9y.jpg', 'https://s.click.aliexpress.com/e/_c4lEFECD', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Miroir LED maquillage', 'miroir-led-maquillage-9o9jl', 'Miroir LED maquillage. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/HTB1tMgmK4TpK1RjSZFMq6zG_VXa1.jpg', 'https://s.click.aliexpress.com/e/_c3jZvj5R', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Support téléphone Garmin', 'support-telephone-garmin-tko31', 'Support téléphone Garmin. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '9500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sd3f1b6d71a0a43169eca090ddc98d2494.jpg', 'https://s.click.aliexpress.com/e/_c3pxiIdx', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-e88tr', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '13000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S9fd3e3c9dcf64627aa8fe77229070972R.jpg', 'https://s.click.aliexpress.com/e/_c3Urh2qd', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Ustensile de cuisine', 'ustensile-de-cuisine-9nar1', 'Ustensile de cuisine. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '17500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S751e44c5e53143d9844d1074aff50046k.jpg', 'https://s.click.aliexpress.com/e/_c4pGXxsV', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-q4hzh', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '8500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S539b2412bde048e0ab78f3a607e58be2I.jpeg', 'https://s.click.aliexpress.com/e/_c316Pam5', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-irall', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '14500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sfaa3440d8b7b408c9c95b2269930bd3dl.jpg', 'https://s.click.aliexpress.com/e/_c2RrqYk1', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-t5bot', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '21500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S79cea748a3c140cda0f19ef632ac64dbn.jpg', 'https://s.click.aliexpress.com/e/_c3rpW3Rx', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche', 'coussin-peluche-ufav5', 'Coussin peluche. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '2000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S8dcab77a1c9f4063be6acc47a2ed2571o.jpg', 'https://s.click.aliexpress.com/e/_c4VJc2Qp', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Coussin peluche', 'coussin-peluche-odv3y', 'Coussin peluche. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '7000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S0d7a85d498b94fae9d4f2c95202839014.jpg', 'https://s.click.aliexpress.com/e/_c37QeNcl', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Montre', 'montre-v6ncx', 'Montre. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '16000', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Se33c2995ae1f47dc89cc195726cabdce0.png', 'https://s.click.aliexpress.com/e/_c3Es2Trx', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-bcq09', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '2500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S518c1618caf440b896da8bd5d6074f8fm.jpg', 'https://s.click.aliexpress.com/e/_c3PXoA57', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Ustensile de cuisine', 'ustensile-de-cuisine-5y8x3', 'Ustensile de cuisine. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '10500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Se6dea7793f764f2f9b96dd9687c052e1O.jpg', 'https://s.click.aliexpress.com/e/_c2u8VH6h', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Câble de charge', 'cable-de-charge-p608w', 'Câble de charge. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12500', 'Prix Fixe', 'Téléphones & Multimédia', 'electronique', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S5c0befde237440e98018c66ee11dadddq.jpg', 'https://s.click.aliexpress.com/e/_c4BNreZF', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Boîte de rangement', 'boite-de-rangement-japbv', 'Boîte de rangement. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '4000', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sea65c0c6b172488a906e0962f12d58bfs.jpg', 'https://s.click.aliexpress.com/e/_c4buqCJX', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Mini ventilateur', 'mini-ventilateur-6d33h', 'Mini ventilateur. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '10500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/Sa8ffe79eb3864d82b9ba0715cf1c84358.jpg', 'https://s.click.aliexpress.com/e/_c3fnSi9L', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Jouet', 'jouet-i4ex2', 'Jouet. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '19500', 'Prix Fixe', 'Sports, Loisirs & Culture', 'sport', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S4de027ff70eb4d219895330081c8717ee.jpg', 'https://s.click.aliexpress.com/e/_c2yEs7J7', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Bouteille / gourde', 'bouteille-gourde-58tgp', 'Bouteille / gourde. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '12500', 'Prix Fixe', 'Maison & Électroménager', 'maison', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/S8f926abe4aba451691f9e18ec62bf2b1P.jpg', 'https://s.click.aliexpress.com/e/_c4NcABGV', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  insert into public.listings (user_id, title, slug, description, price, price_type, category, category_slug, location, image, external_url, order_whatsapp, source, status, premium, is_premium, featured, is_featured, boost_key)
  values (v_owner, 'Jouet', 'jouet-xhltq', 'Jouet. Produit de qualité, livraison au Sénégal. Cliquez sur « Commander sur WhatsApp » pour passer commande.', '11500', 'Prix Fixe', 'Sports, Loisirs & Culture', 'sport', 'Livraison Sénégal', 'https://ae-pic-a1.aliexpress-media.com/kf/HTB1Y2LzaN2rK1RkSnhJq6ykdpXaQ.jpg', 'https://s.click.aliexpress.com/e/_c3gXLtVr', v_wa, 'aliexpress', 'inactive', false, false, false, false, null);

  raise notice '✅ 97 produits (désactivés) importés dans ton compte !';
end $$;

-- Voir les produits : select title, price, status from public.listings where source='aliexpress' order by created_at desc;
-- Tout activer d'un coup (optionnel) : update public.listings set status='active' where source='aliexpress';
